"""refine watchlist and alerts schema

Revision ID: 92be9207f66e
Revises: c827463500da
Create Date: 2026-05-14 15:00:07.506485

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92be9207f66e'
down_revision: Union[str, None] = 'c827463500da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_alerts_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('watchlist_coins', schema=None) as batch_op:
        batch_op.alter_column('watchlist_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_watchlists_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_constraint('fk_watchlists_user_id', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('watchlist_coins', schema=None) as batch_op:
        batch_op.alter_column('watchlist_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_alerts_user_id', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
