"""add_portfolio_engine_tables

Revision ID: bc117fea83a2
Revises: 92be9207f66e
Create Date: 2026-05-19 22:10:23.667980

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc117fea83a2'
down_revision: Union[str, None] = '92be9207f66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index('ix_portfolios_user_default', ['user_id', 'is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=False)

    op.create_table('holdings_cache',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('coin_id', sa.String(length=100), nullable=False),
    sa.Column('coin_symbol', sa.String(length=20), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('avg_cost_basis', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('last_recalculated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_cache_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index('ix_holdings_portfolio_coin', ['portfolio_id', 'coin_id'], unique=True)

    op.create_table('transactions',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('coin_id', sa.String(length=100), nullable=False),
    sa.Column('coin_symbol', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_coin_id'), ['coin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index('ix_txn_portfolio_coin', ['portfolio_id', 'coin_id'], unique=False)
        batch_op.create_index('ix_txn_portfolio_date', ['portfolio_id', 'executed_at'], unique=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_portfolio_date')
        batch_op.drop_index('ix_txn_portfolio_coin')
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_coin_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('holdings_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_holdings_portfolio_coin')
        batch_op.drop_index(batch_op.f('ix_holdings_cache_portfolio_id'))

    op.drop_table('holdings_cache')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))
        batch_op.drop_index('ix_portfolios_user_default')

    op.drop_table('portfolios')
    # ### end Alembic commands ###
